[project]
name = "boekhouding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docxtpl>=0.20.2",
    "jinja2>=3.1.6",
    "jsonschema>=4.26.0",
    "mollie-api-python>=4.0.0",
    "msal>=1.37.0",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "uuid>=1.30",
]
