name: Prek

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv and setup python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.12.1"
          python-version: "3.14"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --group dev

      - name: Run Prek
        run: uv run prek -a
